In [2]:
import numpy as np
import timeit

In [3]:
vetor = np.array([0, 1, 2, 3])
vetor

array([0, 1, 2, 3])

In [4]:
# 1) Crie uma matriz NumPy 100 x 100 contendo somente números pares na primeira linha, números ímpares na segunda e assim sucessivamente.


print("\nMatriz Zerada com Diagonal de Permutações")
matriz_diagonal_permutacao = np.diag(np.array([1, 2, 3, 4]))
print(matriz_diagonal_permutacao)



Matriz Zerada com Diagonal de Permutações
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [6]:
# 8) Usando NumPy, importe o dataset iris mantendo o seu conteúdo intacto.

iris_dataset_url = 'http://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

iris = np.genfromtxt(iris_dataset_url, delimiter=',', dtype='object', encoding='ascii')

nomes = ('spellength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

iris[:3] # imprime as primeiras 3 linhas

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)

In [7]:
# 9) Extraia a coluna *species* do dataset importado na questão anterior para um vetor unidimensional.


iris_1d = np.genfromtxt(iris_dataset_url, delimiter=',', dtype= None, encoding='ascii')

species = np.array([row [4] for row in iris_1d])
species[:200]


array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versic

In [8]:
#10) Calcule a média, mediana e desvio padrão da primeira coluna (sepallength) do dataset Iris.


sepallength = np.genfromtxt(iris_dataset_url, delimiter=',', dtype='float', usecols=[0])

media = np.mean(sepallength)
mediana = np.median(sepallength)
desvio_padrao = np.std(sepallength)

print(sepallength)
print('Média = {:.2f}, Mediana = {:.1f}, DP = {:.4F}'.format(media, mediana, desvio_padrao))

[5.1 4.9 4.7 4.6 5.  5.4 4.6 5.  4.4 4.9 5.4 4.8 4.8 4.3 5.8 5.7 5.4 5.1
 5.7 5.1 5.4 5.1 4.6 5.1 4.8 5.  5.  5.2 5.2 4.7 4.8 5.4 5.2 5.5 4.9 5.
 5.5 4.9 4.4 5.1 5.  4.5 4.4 5.  5.1 4.8 5.1 4.6 5.3 5.  7.  6.4 6.9 5.5
 6.5 5.7 6.3 4.9 6.6 5.2 5.  5.9 6.  6.1 5.6 6.7 5.6 5.8 6.2 5.6 5.9 6.1
 6.3 6.1 6.4 6.6 6.8 6.7 6.  5.7 5.5 5.5 5.8 6.  5.4 6.  6.7 6.3 5.6 5.5
 5.5 6.1 5.8 5.  5.6 5.7 5.7 6.2 5.1 5.7 6.3 5.8 7.1 6.3 6.5 7.6 4.9 7.3
 6.7 7.2 6.5 6.4 6.8 5.7 5.8 6.4 6.5 7.7 7.7 6.  6.9 5.6 7.7 6.3 6.7 7.2
 6.2 6.1 6.4 7.2 7.4 7.9 6.4 6.3 6.1 7.7 6.3 6.4 6.  6.9 6.7 6.9 5.8 6.8
 6.7 6.7 6.3 6.5 6.2 5.9]
Média = 5.84, Mediana = 5.8, DP = 0.8253


In [9]:
# 11)  Normalize a coluna (sepallength) do dataset iris de tal forma que o valor mínimo seja
# zero (0) e o valor máximo seja 1.

sepal_length_max = sepallength.max()
sepal_length_min = sepallength.min()


# se o mínimo for 1 e o máximo for 10, por exemplo, 0 = 1 e 10 = 1

# método 1

sepallength_normalizada = (sepallength - sepal_length_min) / (sepal_length_max - sepal_length_min)

print(sepallength_normalizada)


[0.22222222 0.16666667 0.11111111 0.08333333 0.19444444 0.30555556
 0.08333333 0.19444444 0.02777778 0.16666667 0.30555556 0.13888889
 0.13888889 0.         0.41666667 0.38888889 0.30555556 0.22222222
 0.38888889 0.22222222 0.30555556 0.22222222 0.08333333 0.22222222
 0.13888889 0.19444444 0.19444444 0.25       0.25       0.11111111
 0.13888889 0.30555556 0.25       0.33333333 0.16666667 0.19444444
 0.33333333 0.16666667 0.02777778 0.22222222 0.19444444 0.05555556
 0.02777778 0.19444444 0.22222222 0.13888889 0.22222222 0.08333333
 0.27777778 0.19444444 0.75       0.58333333 0.72222222 0.33333333
 0.61111111 0.38888889 0.55555556 0.16666667 0.63888889 0.25
 0.19444444 0.44444444 0.47222222 0.5        0.36111111 0.66666667
 0.36111111 0.41666667 0.52777778 0.36111111 0.44444444 0.5
 0.55555556 0.5        0.58333333 0.63888889 0.69444444 0.66666667
 0.47222222 0.38888889 0.33333333 0.33333333 0.41666667 0.47222222
 0.30555556 0.47222222 0.66666667 0.55555556 0.36111111 0.33333333
 0.33333

In [10]:
# 12) Encontre o 5º e o 95º percentil do comprimento das pétalas (sepallength) do dataset Iris.

np.percentile(sepallength, q=[5,95])

array([4.6  , 7.255])

In [11]:
# 13) Encontre a quantidade de valores ausentes, bem como a posição deles da 
# primeira coluna da coluna comprimento das pétalas (sepallength), dentro do vetor abaixo:


iris_2d = np.genfromtxt(iris_dataset_url, delimiter=',', dtype='float', usecols=[0,1,2,3], encoding='ascii')
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

print('Quantidade de Valores Ausentes: ', np.isnan(iris_2d[:,0]).sum())
print('Posição dos valores Ausentes: ', np.where(np.isnan(iris_2d[:,0])))

Quantidade de Valores Ausentes:  6
Posição dos valores Ausentes:  (array([ 15, 126, 127, 132, 136, 138], dtype=int64),)


In [12]:
# 14) Filtre o vetor iris_2d do exercício anterior para que ele tenha: 
# (terceira coluna (petallength) > 1.5) && (primeira coluna (sepallength) < 5.0)


iris_2d = np.genfromtxt(iris_dataset_url, delimiter=',', dtype='float', usecols=[0,1,2,3], encoding='ascii')

condicao = (iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] <5.0)
iris_2d[condicao]

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

In [15]:
# 15) Selecione as linhas do vetor iris_2d que não contenham valores nan (Not a Number).

iris_2d = np.genfromtxt(iris_dataset_url, delimiter=',', dtype='float', usecols=[0,1,2,3], encoding='ascii')
iris_2d[np.random.randint(150, size=20), np.random.randint(3, size=20)] = np.nan
condicao = (np.isnan(iris_2d).any(axis=1))
print(iris_2d[~condicao])


[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.4 3.9 1.3 0.4]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.  1.3]
 [5.7 2.8 4.5 1.3]
 [6.3 3.3 4.7 1.6]
 [4.9 2.4 3.3 1. ]
 [6.6 2.9 4.6 1.3]
 [5.2 2.7 3.

In [16]:
# 16) Encontre a correlação entre a primeira coluna (sepallength) e a (terceira coluna (petallength) no vetor iris_2d.

iris_2d = np.genfromtxt(iris_dataset_url, delimiter=',', dtype='float', usecols=[0,1,2,3])
correlacao = np.corrcoef(iris_2d[:,0], iris_2d[:,2])

print('A Correlação é: ' + str(correlacao[0,1]))


A Correlação é : 0.8717541573048718


In [20]:
# 17) Verifique se o vetor iris_2d possui qualquer valor faltante, caso possui deverá retornar True caso contrário False.

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

np.isnan(iris_2d).any()


False

In [21]:
# 18) Substitua todas as ocorrências de nan (Not a Number) por zeros em um vetor NumPy.

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

np.place(iris_2d, np.isnan(iris_2d), [0])
print(iris_2d)


[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 0.  1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 0.  1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [0.  3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [0.  4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 0.  0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [23]:
# 19) Encontre e conte os valores únicos da coluna species

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

print(np.unique(iris[:,4]))

[b'Iris-setosa' b'Iris-versicolor' b'Iris-virginica']


In [26]:
# 20) Mapeie terceira coluna (petallength) de tal forma que os valores numéricos sejam substituídos por valores textuais, seguindo de acordo com a tabela abaixo:

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
nomes = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

petallength = np.array(iris[:,2], dtype='float')

for i, item in enumerate(petallength):
    if (item < 3):
        iris[i][2] = "Pequena"
    elif (item >= 3 and item < 5):
        iris[i][2] = "Média"
    else:
        iris[i][2] = "Grande"
    
print(iris)


[[b'5.1' b'3.5' 'Pequena' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' 'Pequena' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' 'Pequena' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' 'Pequena' b'0.2' b'Iris-setosa']
 [b'5.0' b'3.6' 'Pequena' b'0.2' b'Iris-setosa']
 [b'5.4' b'3.9' 'Pequena' b'0.4' b'Iris-setosa']
 [b'4.6' b'3.4' 'Pequena' b'0.3' b'Iris-setosa']
 [b'5.0' b'3.4' 'Pequena' b'0.2' b'Iris-setosa']
 [b'4.4' b'2.9' 'Pequena' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.1' 'Pequena' b'0.1' b'Iris-setosa']
 [b'5.4' b'3.7' 'Pequena' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.4' 'Pequena' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.0' 'Pequena' b'0.1' b'Iris-setosa']
 [b'4.3' b'3.0' 'Pequena' b'0.1' b'Iris-setosa']
 [b'5.8' b'4.0' 'Pequena' b'0.2' b'Iris-setosa']
 [b'5.7' b'4.4' 'Pequena' b'0.4' b'Iris-setosa']
 [b'5.4' b'3.9' 'Pequena' b'0.4' b'Iris-setosa']
 [b'5.1' b'3.5' 'Pequena' b'0.3' b'Iris-setosa']
 [b'5.7' b'3.8' 'Pequena' b'0.3' b'Iris-setosa']
 [b'5.1' b'3.8' 'Pequena' b'0.3' b'Iris-setosa']
 [b'5.4' b'3.4' 'Peq

In [27]:
# 21) Crie uma nova coluna chamada volume, preenchida com dados resultantes da seguinte equação:

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')
nomes = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

petallength = np.array(iris_2d[:,2], dtype='float')
sepallength = np.array(iris_2d[:,2], dtype='float')
volume = []

for i, item in enumerate(petallength):
    volume.append((np.pi*item*sepallength[i]**2)/3)

iris_2d_volume = np.c_[np.array(iris_2d), np.array(volume)]
    
print(iris_2d_volume)



[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa' 2.8735100804834635]
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa' 2.8735100804834635]
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa' 2.3006930199789255]
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa' 3.5342917352885173]
 [b'5.0' b'3.6' b'1.4' b'0.2' b'Iris-setosa' 2.8735100804834635]
 [b'5.4' b'3.9' b'1.7' b'0.4' b'Iris-setosa' 5.144881569028883]
 [b'4.6' b'3.4' b'1.4' b'0.3' b'Iris-setosa' 2.8735100804834635]
 [b'5.0' b'3.4' b'1.5' b'0.2' b'Iris-setosa' 3.5342917352885173]
 [b'4.4' b'2.9' b'1.4' b'0.2' b'Iris-setosa' 2.8735100804834635]
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa' 3.5342917352885173]
 [b'5.4' b'3.7' b'1.5' b'0.2' b'Iris-setosa' 3.5342917352885173]
 [b'4.8' b'3.4' b'1.6' b'0.2' b'Iris-setosa' 4.289321169701265]
 [b'4.8' b'3.0' b'1.4' b'0.1' b'Iris-setosa' 2.8735100804834635]
 [b'4.3' b'3.0' b'1.1' b'0.1' b'Iris-setosa' 1.393819940642672]
 [b'5.8' b'4.0' b'1.2' b'0.2' b'Iris-setosa' 1.8095573684677209]
 [b'5.7' b'4.4' b'1.5' b'0.4

In [28]:
# 22) Usando NumPy e o dataset iris responda: Qual é o segundo maior valor de 
# comprimento de pétala (petallength) da espécie setosa?

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
nomes = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

condicao = (iris[:,4] == b'Iris-setosa')

iris_2d_setosa = iris[condicao]
petallength = np.unique(np.sort(iris_2d_setosa[:,2]))

print('Segundo maior Petallength da espécie setosa: ' + str(petallength[len(petallength)-2]))



Segundo maior Petallength da espécie setosa: b'1.7'


In [32]:
# 23) Ordene o dataset iris com base na coluna sepallength de maneira crescente.

dtype = [('sepallength', float), ('sepalwidth', float), ('petallength', float), ('petalwidth', float), ('species', 'S20')]
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype=dtype)

np.sort(iris, order='sepallength')

array([(4.3, 3. , 1.1, 0.1, b'Iris-setosa'),
       (4.4, 2.9, 1.4, 0.2, b'Iris-setosa'),
       (4.4, 3. , 1.3, 0.2, b'Iris-setosa'),
       (4.4, 3.2, 1.3, 0.2, b'Iris-setosa'),
       (4.5, 2.3, 1.3, 0.3, b'Iris-setosa'),
       (4.6, 3.1, 1.5, 0.2, b'Iris-setosa'),
       (4.6, 3.2, 1.4, 0.2, b'Iris-setosa'),
       (4.6, 3.4, 1.4, 0.3, b'Iris-setosa'),
       (4.6, 3.6, 1. , 0.2, b'Iris-setosa'),
       (4.7, 3.2, 1.3, 0.2, b'Iris-setosa'),
       (4.7, 3.2, 1.6, 0.2, b'Iris-setosa'),
       (4.8, 3. , 1.4, 0.1, b'Iris-setosa'),
       (4.8, 3. , 1.4, 0.3, b'Iris-setosa'),
       (4.8, 3.1, 1.6, 0.2, b'Iris-setosa'),
       (4.8, 3.4, 1.6, 0.2, b'Iris-setosa'),
       (4.8, 3.4, 1.9, 0.2, b'Iris-setosa'),
       (4.9, 2.4, 3.3, 1. , b'Iris-versicolor'),
       (4.9, 2.5, 4.5, 1.7, b'Iris-virginica'),
       (4.9, 3. , 1.4, 0.2, b'Iris-setosa'),
       (4.9, 3.1, 1.5, 0.1, b'Iris-setosa'),
       (4.9, 3.1, 1.5, 0.1, b'Iris-setosa'),
       (4.9, 3.1, 1.5, 0.1, b'Iris-setosa'),
   

In [33]:
#24) Encontre o valor mais frequente da terceira coluna (petallength) do dataset iris.

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
nomes = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

valores, contador = np.unique(iris[:,2], return_counts=True)
posicao = np.where(contador == contador.max())

print('O valor mais frequente da coluna Petallength é: ' + str(valores[int(posicao[0])]))



O valor mais frequente da coluna Petallength é: b'1.5'


In [35]:
# 25) Encontre a posição da primeira ocorrência de um valor maior do que 1.0 da quarta coluna (petalwidth) do dataset iris.

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='float')
posicao = np.where(iris[:,3] > 1)
list_posicao = list(posicao[0])
print('A posição da primeira ocorrencia de valor maior que 1 é: ' + str(int(list_posicao[0])))

A posição da primeira ocorrencia de valor maior que 1 é: 50


In [38]:
# 26) Obtenha a posição dos top 5 valores maximos do vetor abaixo:

np.random.seed(100)
vetor = np.random.uniform(1,50, 20)
print(vetor[np.argsort(vetor)[-5:]])


[40.99501269 41.466785   42.39403048 44.67477576 48.95256545]


In [ ]:
# 27) Encontre a média de uma coluna numérica agrupada por uma coluna categórica em uma matriz (vetor numpy 2D)

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

